import { describe, it, expect } from "vitest";
import { containerVariants, createContainer } from "./container.js";

/* -------------------------------------------------------
 * 📦 TEST: containerVariants (CVA output)
 * - Verifies classes generated by variants & sizes
 * - Ensures token-based classes appear correctly
 * ------------------------------------------------------*/
describe("containerVariants", () => {
  
  it("applies default variant and size", () => {
    const result = containerVariants();

    // Default size is xl
    expect(result).toContain("max-w-screen-xl");
  });

  it("applies section variant padding", () => {
    const result = containerVariants({ variant: "section" });

    expect(result).toContain("py-16");
  });

  it("applies card variant styling", () => {
    const result = containerVariants({ variant: "card" });

    expect(result).toContain("rounded-(--radius-2xl)");
    expect(result).toContain("border-(--border-default)");
    expect(result).toContain("bg-(--surface-base)");
    expect(result).toContain("shadow-(--shadow-sm)");
    expect(result).toContain("p-6");
  });

  it("fluid variant removes max-width AND padding", () => {
    const result = containerVariants({ variant: "fluid" });

    // Full width
    expect(result).toContain("w-full");

    // MUST override default size variant (xl)
    expect(result).toContain("!max-w-none");

    // Should NOT include padding or centering utilities
    expect(result).not.toContain("px-4");
    expect(result).not.toContain("sm:px-6");
    expect(result).not.toContain("lg:px-8");
    expect(result).not.toContain("mx-auto");
  });

  it("applies size overrides", () => {
    const result = containerVariants({ size: "md" });

    expect(result).toContain("max-w-screen-md");
  });
});


/* -------------------------------------------------------
 * 🧱 TEST: createContainer (DOM element creation)
 * - Ensures element creation, innerHTML, attributes,
 *   and class merging works as expected.
 * ------------------------------------------------------*/
describe("createContainer", () => {

  it("creates a div element", () => {
    const container = createContainer();
    expect(container.tagName).toBe("DIV");
  });

  it("applies class names from CVA", () => {
    const container = createContainer({ variant: "section" });
    expect(container.className).toContain("py-16");
  });

  it("sets innerHTML when children is string", () => {
    const container = createContainer({ children: "<p>Hello</p>" });
    expect(container.innerHTML).toContain("Hello");
  });

  it("adds attributes correctly", () => {
    const container = createContainer({
      attributes: { id: "test-box", "data-custom": "ok" },
    });

    expect(container.getAttribute("id")).toBe("test-box");
    expect(container.getAttribute("data-custom")).toBe("ok");
  });
});
